services:
  webserver:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
